// <auto-generated />
using System;
using BonosCarrosWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BonosCarrosWeb.Data.Migrations
{
    [DbContext(typeof(CarrosDbContext))]
    [Migration("20231211233117_RelacionamentoCarrosMarcas")]
    partial class RelacionamentoCarrosMarcas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BonosCarrosWeb.Models.Carro", b =>
                {
                    b.Property<int>("CarroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarroId"));

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Disponibilidade")
                        .HasColumnType("bit");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.HasKey("CarroId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Carro");
                });

            modelBuilder.Entity("BonosCarrosWeb.Models.Designer", b =>
                {
                    b.Property<int>("DesignerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignerId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DesignerId");

                    b.ToTable("Designer");
                });

            modelBuilder.Entity("BonosCarrosWeb.Models.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarcaId");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("CarroDesigner", b =>
                {
                    b.Property<int>("ListaCarrosCarroId")
                        .HasColumnType("int");

                    b.Property<int>("ListaDesignersDesignerId")
                        .HasColumnType("int");

                    b.HasKey("ListaCarrosCarroId", "ListaDesignersDesignerId");

                    b.HasIndex("ListaDesignersDesignerId");

                    b.ToTable("CarroDesigner");
                });

            modelBuilder.Entity("BonosCarrosWeb.Models.Carro", b =>
                {
                    b.HasOne("BonosCarrosWeb.Models.Marca", null)
                        .WithMany("ListaCarros")
                        .HasForeignKey("MarcaId");
                });

            modelBuilder.Entity("CarroDesigner", b =>
                {
                    b.HasOne("BonosCarrosWeb.Models.Carro", null)
                        .WithMany()
                        .HasForeignKey("ListaCarrosCarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BonosCarrosWeb.Models.Designer", null)
                        .WithMany()
                        .HasForeignKey("ListaDesignersDesignerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BonosCarrosWeb.Models.Marca", b =>
                {
                    b.Navigation("ListaCarros");
                });
#pragma warning restore 612, 618
        }
    }
}
