

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using BonosCarrosWeb.Models;
//
//    var cepResponse = CepResponse.FromJson(jsonString);

namespace BonosCarrosWeb.Models
{
	using System;
	using System.Collections.Generic;

	using System.Globalization;
	using Newtonsoft.Json;
	using Newtonsoft.Json.Converters;

	public partial class CepResponse
	{
		[JsonProperty("cep")]
		public string Cep { get; set; }

		[JsonProperty("logradouro")]
		public string Logradouro { get; set; }

		[JsonProperty("complemento")]
		public string Complemento { get; set; }

		[JsonProperty("bairro")]
		public string Bairro { get; set; }

		[JsonProperty("localidade")]
		public string Localidade { get; set; }

		[JsonProperty("uf")]
		public string Uf { get; set; }

		[JsonProperty("ibge")]
		[JsonConverter(typeof(ParseStringConverter))]
		public long Ibge { get; set; }

		[JsonProperty("gia")]
		public string Gia { get; set; }

		[JsonProperty("ddd")]
		[JsonConverter(typeof(ParseStringConverter))]
		public long Ddd { get; set; }

		[JsonProperty("siafi")]
		[JsonConverter(typeof(ParseStringConverter))]
		public long Siafi { get; set; }
	}

	public partial class CepResponse
	{
		public static CepResponse FromJson(string json) => JsonConvert.DeserializeObject<CepResponse>(json, BonosCarrosWeb.Models.Converter.Settings);
	}

	public static class Serialize
	{
		public static string ToJson(this CepResponse self) => JsonConvert.SerializeObject(self, BonosCarrosWeb.Models.Converter.Settings);
	}

	internal static class Converter
	{
		public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
		{
			MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
			DateParseHandling = DateParseHandling.None,
			Converters =
			{
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
		};
	}

	internal class ParseStringConverter : JsonConverter
	{
		public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

		public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
		{
			if (reader.TokenType == JsonToken.Null) return null;
			var value = serializer.Deserialize<string>(reader);
			long l;
			if (Int64.TryParse(value, out l))
			{
				return l;
			}
			throw new Exception("Cannot unmarshal type long");
		}

		public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
		{
			if (untypedValue == null)
			{
				serializer.Serialize(writer, null);
				return;
			}
			var value = (long)untypedValue;
			serializer.Serialize(writer, value.ToString());
			return;
		}

		public static readonly ParseStringConverter Singleton = new ParseStringConverter();
	}
}
